# Generated by Django 5.0.1 on 2024-02-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_register_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.AddField(
            model_name='register',
            name='Loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bapp.login'),
        ),
    ]
