# Generated by Django 5.0.1 on 2024-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0003_remove_register_address_register_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='resreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('reslic', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
