# Generated by Django 5.0.1 on 2024-02-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0004_resreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='resreg',
            name='resid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bapp.login'),
        ),
    ]
