# Generated by Django 5.0.1 on 2024-02-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0005_resreg_resid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resreg',
            name='password',
        ),
    ]
