# Generated by Django 5.0.1 on 2024-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0006_remove_resreg_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(upload_to='')),
                ('disc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
