# Generated by Django 5.0.1 on 2024-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0008_rename_image_product_pimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='resreg',
            name='rimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
